#!/usr/bin/env bash
set -u

#echo statement - starting of the script
echo "Script dlorg started"

#settings
source_folder="$HOME/Downloads"
destination_folder="$source_folder/Sorted"
other_folder="$destination_folder/Other"

#the file sorting
function file_sorting {
##uppercase_name="" #IMPROVEMENT: lowercase copy of extension for VIP check (JPG vs jpg)
file_name="$1" #inotifywait - the doorbell
base_name="${file_name%.*}" #keeps the filename by removing file extension
extension="${file_name##*.}" #keeps the extension of the file
##extension="${uppercase_name##*.}" #IMPROVEMENT: uppercase names/extension get renamed

if [ "$file_name" = "$extension" ]; then
    basket_folder="Other"
else 
    case "$extension" in
        jpg|jpeg|png|gif|webp|svg|bmp) basket_folder="Pictures" ;;
        mp4|mkv|avi|mov|webm) basket_folder="Videos" ;;
        mp3|flac|wav|ogg|m4a) basket_folder="Audio" ;;
        pdf|doc|docx|odt|txt|md|rtf) basket_folder="Documents" ;;
        xls|xlsx|ods|csv|ppt|pptx) basket_folder="Spreadsheets_Slides" ;;
        zip|tar|gz|7z|rar|xz) basket_folder="Archives" ;;
        deb|rpm|exe|msi|appimage|iso) basket_folder="Installers" ;;
        sh|py|js|html|css|c|json|cpp|cs) basket_folder="Code" ;;
        *) basket_folder="Other" ;;
    esac
fi

mkdir -p "$destination_folder/$basket_folder"

#while loop for same name files to add a counter to it > example: filename_1.jpg > filename_2.jpg
candidate_name="$file_name"
counter=1
while [ -e "$destination_folder/$basket_folder/$candidate_name" ]; do
    if [ "$file_name" = "$extension" ]; then
        candidate_name="${file_name}_${counter}"
    else 
        candidate_name="${base_name}_${counter}.${extension}"
    fi
    counter=$((counter + 1)) #The actual counter that goes +1 for every file that has the same name.
done


mv "$source_folder/$file_name" "$destination_folder/$basket_folder/$candidate_name"



}

#echo statement - the script is running
echo "dlorg ready: Listening for close_write/moved_to events in $source_folder"

#the bell to tell bouncer to start sorting the files that enter Downloads
inotifywait -me moved_to,close_write --format '%f' "$source_folder" |
while read new_file; do
    file_sorting "$new_file"
done 

#fake jobs for debugging
##file_sorting "cat.jpg"
##file_sorting "name.date.2005.pdf"
##file_sorting "song.mp3"
##file_sorting "README"
##file_sorting "data.data"

# monitor folder and have bouncer sort
# make sure the basket exist, if not make basket on demand
# same name check, if same name add numeric value to sort same name files.
# move the files